/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

import regisry from "@/registry.json";

const getRegistryComponentItemConfig = (item) => {
  return {
    [item.name]: {
      name: item.name,
      description: item.description || "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: item.files,
      component: React.lazy(async () => {
        const mod = await import(`@/registry/wandry-ui/${item.name}.tsx`);
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    [`${item.name}-demo`]: {
      name: `${item.name}-demo`,
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: item.files,
      component: React.lazy(async () => {
        const mod = await import(`@/registry/examples/${item.name}-demo.tsx`);
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
  };
};

const getRegistryBlockItemConfig = (item) => {
  return {
    [item.name]: {
      name: item.name,
      description: item.description || "",
      type: "registry:block",
      registryDependencies: undefined,
      files: item.files,
      component: React.lazy(async () => {
        const mod = await import(
          `@/registry/wandry-ui/blocks/${item.name}/page.tsx`
        );
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    [`${item.name}-demo`]: {
      name: `${item.name}-demo`,
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: item.files,
      component: React.lazy(async () => {
        const mod = await import(`@/registry/examples/${item.name}-demo.tsx`);
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
  };
};

const components = regisry.items
  .filter((item) => item.type === "registry:component")
  .reduce((acc, item) => {
    return { ...acc, ...getRegistryComponentItemConfig(item) };
  }, {});

const blocks = regisry.items
  .filter((item) => item.type === "registry:block")
  .reduce((acc, item) => {
    return { ...acc, ...getRegistryBlockItemConfig(item) };
  }, {});

export const Index: Record<string, any> = {
  ...components,
  ...blocks,
};
