/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

import regisry from "@/registry.json";

const getRegistryItemConfig = (item) => {
  return {
    [item.name]: {
      name: item.name,
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: item.files,
      component: React.lazy(async () => {
        const mod = await import(`@/registry/wandry-ui/${item.name}.tsx`);
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    [`${item.name}-demo`]: {
      name: `${item.name}-demo`,
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: item.files,
      component: React.lazy(async () => {
        const mod = await import(`@/registry/examples/${item.name}-demo.tsx`);
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
  };
};

export const Index: Record<string, any> = regisry.items.reduce((acc, item) => {
  return { ...acc, ...getRegistryItemConfig(item) };
}, {});
