// @ts-nocheck -- skip type checking
import * as docs_12 from "../content/docs/components/textarea-field.mdx?collection=docs&hash=1760890015084"
import * as docs_11 from "../content/docs/components/text-field.mdx?collection=docs&hash=1760890015084"
import * as docs_10 from "../content/docs/components/switch-field.mdx?collection=docs&hash=1760890015084"
import * as docs_9 from "../content/docs/components/select-field.mdx?collection=docs&hash=1760890015084"
import * as docs_8 from "../content/docs/components/radio-field.mdx?collection=docs&hash=1760890015084"
import * as docs_7 from "../content/docs/components/password-field.mdx?collection=docs&hash=1760890015084"
import * as docs_6 from "../content/docs/components/input-otp-field.mdx?collection=docs&hash=1760890015084"
import * as docs_5 from "../content/docs/components/index.mdx?collection=docs&hash=1760890015084"
import * as docs_4 from "../content/docs/components/checkbox-field.mdx?collection=docs&hash=1760890015084"
import * as docs_3 from "../content/docs/components/async-autocomplete-field.mdx?collection=docs&hash=1760890015084"
import * as docs_2 from "../content/docs/wandry-inertia-form.mdx?collection=docs&hash=1760890015084"
import * as docs_1 from "../content/docs/installation.mdx?collection=docs&hash=1760890015084"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1760890015084"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"installation.mdx","fullPath":"content/docs/installation.mdx"}, data: docs_1 }, { info: {"path":"wandry-inertia-form.mdx","fullPath":"content/docs/wandry-inertia-form.mdx"}, data: docs_2 }, { info: {"path":"components/async-autocomplete-field.mdx","fullPath":"content/docs/components/async-autocomplete-field.mdx"}, data: docs_3 }, { info: {"path":"components/checkbox-field.mdx","fullPath":"content/docs/components/checkbox-field.mdx"}, data: docs_4 }, { info: {"path":"components/index.mdx","fullPath":"content/docs/components/index.mdx"}, data: docs_5 }, { info: {"path":"components/input-otp-field.mdx","fullPath":"content/docs/components/input-otp-field.mdx"}, data: docs_6 }, { info: {"path":"components/password-field.mdx","fullPath":"content/docs/components/password-field.mdx"}, data: docs_7 }, { info: {"path":"components/radio-field.mdx","fullPath":"content/docs/components/radio-field.mdx"}, data: docs_8 }, { info: {"path":"components/select-field.mdx","fullPath":"content/docs/components/select-field.mdx"}, data: docs_9 }, { info: {"path":"components/switch-field.mdx","fullPath":"content/docs/components/switch-field.mdx"}, data: docs_10 }, { info: {"path":"components/text-field.mdx","fullPath":"content/docs/components/text-field.mdx"}, data: docs_11 }, { info: {"path":"components/textarea-field.mdx","fullPath":"content/docs/components/textarea-field.mdx"}, data: docs_12 }], [])